# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TF_VER_application_name: epocher

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terrafrom
        uses: hashicorp/setup-terraform@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2.0.0

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true


  dev_deployment:
    runs-on: ubuntu-latest
    environment: Dev
    
    env:
          TF_VAR_environment: "dev"
          TF_VER_application_name: "epocher"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      # TODO: CHeck why is not chekcing
      - uses: actions/checkout@v3
      - name: Build lambda
        run: sh build-lambda.sh
      - name: Terraform innit
        run: terraform init -backend-config="key=tfstate"
        working-directory: "terraform"

      - name: Terraform plan
        run: terraform plan
        working-directory: "terraform"

      #- name: Terraform apply on branch main
      #  if: github.ref == 'refs/heads/main'
      #  run: terraform apply -auto-approve
      #  working-directory: "terraform"

      - name: Terraform destroy on branch destroy
        if: github.ref == 'refs/heads/destroy'
        run: terraform destroy -auto-approve
        working-directory: "terraform"

  #test_dev:
  #  runs-on: ubuntu-latest

  prod_deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply on branch main
        env:
          TF_VAR_Environment: "prod"
          TF_VER_application_name: "epocher"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform destroy on branch destroy
        if: github.ref == 'refs/heads/destroy'
        run: terraform destroy -auto-approve
